# Current highest ranking in the cell
- type: job
  id: SynCellCommander
  name: job-name-cellleader
  description: job-description-cellleader
  playTimeTracker: JobCellComm
  setPreference: true
  startingGear: CellCommanderGear
  icon: "JobIconSyndicate"
  supervisors: job-supervisors-HC
  canBeAntag: false
  weight: 5
  accessGroups:
  - GeneralAccess
  access:
  - SyndicateAgent
  special:
  - !type:AddImplantSpecial
    implants: [ RadioImplant, DeathRattleImplant ]
  whitelisted: true # Frontier

- type: startingGear
  id: CellCommanderGear
  equipment:
    mask: ClothingMaskGasVoiceChameleon
    id: SyndieCommPDA
    ears: ClothingHeadsetGrey
    back: ClothingBackpackDuffelSyndicate
    pocket1: AgentIDCard
    pocket2: NFWeaponEnergyPistolDisabler
    jumpsuit: ClothingUniformJumpsuitOperative
    outerClothing: ClothingOuterHardsuitSyndie
  storage:
    back:
    - PinpointerSyndicatePOI

# Basic officer
- type: job
  id: SynCellOfficer
  name: job-name-cellofficer
  description: job-description-cellofficer
  playTimeTracker: JobCellOff
  setPreference: true
  startingGear: CellOfficerGear
  icon: "JobIconSyndicate"
  supervisors: job-supervisors-CL
  canBeAntag: false
  weight: 4
  accessGroups:
  - GeneralAccess
  access:
  - SyndicateAgent
  special:
  - !type:AddImplantSpecial
    implants: [ RadioImplant, DeathRattleImplant ]
  whitelisted: true # Frontier

- type: startingGear
  id: CellOfficerGear
  equipment:
    mask: ClothingMaskGasVoiceChameleon
    id: SyndieOffPDA
    ears: ClothingHeadsetGrey
    back: ClothingBackpackDuffelSyndicate
    pocket1: AgentIDCard
    pocket2: NFWeaponEnergyPistolDisabler
    jumpsuit: ClothingUniformJumpsuitOperative
    outerClothing: ClothingOuterHardsuitSyndie
  storage:
    back:
    - PinpointerSyndicatePOI

# Agents/ops with notable capability in a field(s)
- type: job
  id: SynCellSpecialist
  name: job-name-cellspecialist
  description: job-description-cellspecialist
  playTimeTracker: JobCellSpec
  setPreference: true
  startingGear: CellSpecialistGear
  icon: "JobIconSyndicate"
  supervisors: job-supervisors-CO
  canBeAntag: false
  weight: 3
  accessGroups:
  - GeneralAccess
  access:
  - SyndicateAgent
  special:
  - !type:AddImplantSpecial
    implants: [ RadioImplant, DeathRattleImplant ]
  whitelisted: true # Frontier

- type: startingGear
  id: CellSpecialistGear
  equipment:
    mask: ClothingMaskGasVoiceChameleon
    id: SyndieSpecPDA
    ears: ClothingHeadsetGrey
    back: ClothingBackpackDuffelSyndicate
    pocket1: AgentIDCard
    pocket2: NFWeaponEnergyPistolDisabler
    jumpsuit: ClothingUniformJumpsuitOperative
    outerClothing: ClothingOuterHardsuitSyndie
  storage:
    back:
    - PinpointerSyndicatePOI

# Basic agents/ops
- type: job
  id: SynCellAgent
  name: job-name-cellagent
  description: job-description-cellagent
  playTimeTracker: JobCellOp
  setPreference: true
  startingGear: CellAgentGear
  icon: "JobIconSyndicate"
  supervisors: job-supervisors-CO
  canBeAntag: false
  weight: 2
  accessGroups:
  - GeneralAccess
  access:
  - SyndicateAgent
  special:
  - !type:AddImplantSpecial
    implants: [ RadioImplant, DeathRattleImplant ]
  whitelisted: true # Frontier

- type: startingGear
  id: CellAgentGear
  equipment:
    mask: ClothingMaskGasVoiceChameleon
    id: SyndieAgentPDA
    ears: ClothingHeadsetGrey
    back: ClothingBackpackDuffelSyndicate
    pocket1: AgentIDCard
    pocket2: NFWeaponEnergyPistolDisabler
    jumpsuit: ClothingUniformJumpsuitOperative
    outerClothing: ClothingOuterHardsuitSyndie
  storage:
    back:
    - PinpointerSyndicatePOI

# The quote unquote shitter role
- type: job
  id: SynCellProspect
  name: job-name-cellprospect
  description: job-description-cellprospect
  playTimeTracker: JobCellPros
  setPreference: true
  startingGear: SynCellProspectGearEVA
  icon: "JobIconSyndicate"
  supervisors: job-supervisors-cell
  canBeAntag: false
  weight: 1
  accessGroups:
  - GeneralAccess
  access:
  - SyndicateAgent
  special:
  - !type:AddImplantSpecial
    implants: [ RadioImplant, DeathRattleImplant ]
  whitelisted: true # Frontier

- type: startingGear
  id: SynCellProspectGear
  equipment:
    mask: ClothingMaskGasVoiceChameleon
    id: SyndieProspectPDA
    ears: ClothingHeadsetGrey
    back: ClothingBackpackDuffelSyndicate
    pocket1: CardScJackOfHeartsBlack
    pocket2: NFWeaponEnergyPistolDisabler
    jumpsuit: ClothingUniformJumpsuitOperative
    outerClothing: ClothingOuterHardsuitSyndie
  storage:
    back:
    - PinpointerSyndicatePOI

# Loadout stuff ClothingOuterHardsuitSyndie

- type: loadout
  id: SynJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative

- type: loadout
  id: SynJumpskirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtOperative

- type: loadout
  id: SynTurtleneck
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndieFormal

- type: loadout
  id: SynTurtleneckSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtSyndieFormalDress

- type: loadout
  id: SynCrop
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperativeCrop

- type: loadout
  id: SynCropSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtOperativeCrop

- type: loadout
  id: SynCropSleeve
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperativeCropSleeves

- type: loadout
  id: SynCropSkirtSleeve
  equipment:
    jumpsuit: ClothingUniformJumpskirtOperativeCropSleeves

- type: loadout
  id: SynBack
  equipment:
    jumpsuit: ClothingBackpackSyndicate

- type: loadout
  id: SynBackDuff
  equipment:
    jumpsuit: ClothingBackpackDuffelSyndicate

- type: loadout
  id: SynBackMess
  equipment:
    jumpsuit: ClothingBackpackMessengerSyndicate
